# Generated by Django 5.0.14 on 2026-06-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                ("user_message", models.TextField(blank=True, null=True)),
                ("ai_response", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="Module/App where the error occurred", max_length=100
                    ),
                ),
                ("error_message", models.TextField()),
                ("stack_trace", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RobotLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("robot_id", models.CharField(default="humanoid_v1", max_length=100)),
                (
                    "level",
                    models.CharField(
                        default="INFO",
                        help_text="Log level (INFO, WARNING, DEBUG)",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RobotStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "robot_id",
                    models.CharField(
                        default="humanoid_v1", max_length=100, unique=True
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                (
                    "battery_level",
                    models.FloatField(
                        default=100.0, help_text="Battery percentage (0.0 to 100.0)"
                    ),
                ),
                ("last_ping", models.DateTimeField(auto_now=True)),
                (
                    "current_mode",
                    models.CharField(
                        default="idle",
                        help_text="Operating mode (e.g. idle, speaking, listening)",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Robot Statuses",
            },
        ),
    ]
